# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.add_btn = QtWidgets.QPushButton(self.frame_2)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_btn = QtWidgets.QPushButton(self.frame_4)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn, 0, QtCore.Qt.AlignLeft)
        self.load_btn = QtWidgets.QPushButton(self.frame_4)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout_2.addWidget(self.load_btn, 0, QtCore.Qt.AlignLeft)
        self.refresh_btn = QtWidgets.QPushButton(self.frame_4)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_2.addWidget(self.refresh_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.delete_all_btn = QtWidgets.QPushButton(self.frame_4)
        self.delete_all_btn.setObjectName("delete_all_btn")
        self.horizontalLayout_2.addWidget(self.delete_all_btn, 0, QtCore.Qt.AlignRight)
        self.delete_btn = QtWidgets.QPushButton(self.frame_4)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_2.addWidget(self.delete_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)  
        self.add_btn.clicked.connect(self.insert_data) 
        self.delete_all_btn.clicked.connect(self.delete_all) 
        self.load_btn.clicked.connect(self.delete_first)
        self.refresh_btn.clicked.connect(self.delete_last)
        self.delete_btn.clicked.connect(self.deleted)
        self.save_btn.clicked.connect(self.msg)  
        self.refresh() 
    # for database connection
    def db(self): 
        import sqlite3 
        conn=sqlite3.connect('main.db') 
        c=conn.cursor()
        command="CREATE TABLE IF NOT EXISTS TODO (TASK TEXT NOT NULL) " 
        c.execute(command) 
        conn.commit()
        return c,conn 
    # to insert data to db 
    def insert_data(self):  
        c=self.db()[0];conn=self.db()[1] 
        data=self.lineEdit.text().strip()
        command="INSERT INTO TODO VALUES(?)"
        if data!="": 
            c=conn.cursor()
            c.execute(command,[data]) 
            conn.commit()
            self.listWidget.addItem(data)
            self.lineEdit.clear() 
        return c,conn 
    #to refresh the listwidget 
    def refresh(self): 
        self.lineEdit.clear()
        self.listWidget.clear()
        c=self.insert_data()[0];conn=self.insert_data()[1]
        Command="SELECT * FROM TODO"
        c.execute(Command) 
        rows=c.fetchall() 
        for row in rows: 
            self.listWidget.addItem(row[0])
    def delete_first(self): 
        c=c=self.db()[0];conn=self.db()[1] 
        c=conn.cursor()
        command="DELETE FROM TODO WHERE rowid=(SELECT MIN(rowid) FROM TODO)" 
        c.execute(command)
        conn.commit()  
        data=self.lineEdit.text()
        self.refresh() 
        self.lineEdit.setText(data)
    
    def delete_all(self): 
        c=self.db()[0];conn=self.db()[1] 
        c=conn.cursor()
        command="DELETE FROM TODO" 
        c.execute(command)  
        conn.commit()
        rows=c.fetchall()  
        data=self.lineEdit.text()
        self.refresh()  
        self.lineEdit.setText(data)
    # to delete the particular task
    def deleted(self): 
        selected=self.listWidget.currentItem()
        c=self.db()[0];conn=self.db()[1]
        if selected!=None: 
            selected=selected.text().strip()
            c=conn.cursor()
            command="DELETE FROM TODO WHERE TASK=?" 
            c.execute(command,[selected])
            conn.commit()
            data=self.lineEdit.text()
            self.refresh()  
            self.lineEdit.setText(data)
    # pop up msg box    
    def msg(self): 
        m=QMessageBox() 
        m.setIcon(QMessageBox.Information) 
        m.setText("no problem it automatically saves the data :-)") 
        m.setWindowTitle("INFO") 
        m.setStandardButtons(QMessageBox.Ok)  
        m.exec_()


    def delete_last(self): 
        c=c=self.db()[0];conn=self.db()[1] 
        c=conn.cursor() 
        data=self.lineEdit.text()
        command="DELETE FROM TODO WHERE rowid=(SELECT MAX(rowid) FROM TODO)" 
        c.execute(command)
        conn.commit() 
        self.refresh() 
        self.lineEdit.setText(data)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ADD TASK"))
        self.add_btn.setText(_translate("MainWindow", "ADD"))
        self.save_btn.setText(_translate("MainWindow", "SAVE"))
        self.load_btn.setText(_translate("MainWindow", "DELETE FIRST"))
        self.refresh_btn.setText(_translate("MainWindow", "DELETE LAST"))
        self.delete_all_btn.setText(_translate("MainWindow", "DELETE ALL"))
        self.delete_btn.setText(_translate("MainWindow", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
